# Site settings
title: Zoologist to Programmer
header-img: img/home-bg.png
email: greenjenniferb@gmail.com
copyright_name: OllieRemus
description: > # this means to ignore newlines until "baseurl:"
  My journey in a huge career change
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  OllieRemus
learn_profile: OllieRemus
email_username: greenjenniferb@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
